export EDEV_WORKSPACE="${EDEV_WORKSPACE:-$HOME/dev}"
export EDEV_PROJECTS_DIR="${EDEV_PROJECTS_DIR:-$EDEV_WORKSPACE/projects}"
export EDEV_APPS_DIR="${EDEV_APPS_DIR:-$HOME/apps}"

export EDEV_TOMCAT_VERSION="${EDEV_TOMCAT_VERSION:-9.0.118}"
export EDEV_WILDFLY_VERSION="${EDEV_WILDFLY_VERSION:-26.1.3.Final}"

export EDEV_TOMCAT_HOME="${EDEV_TOMCAT_HOME:-$EDEV_APPS_DIR/tomcats/tomcat9}"
export EDEV_WILDFLY_HOME="${EDEV_WILDFLY_HOME:-$EDEV_APPS_DIR/jbosses/wildfly26}"
export EDEV_JDKS_HOME="${EDEV_JDKS_HOME:-$EDEV_APPS_DIR/jdks}"
export EDEV_JAVA6_HOME="${EDEV_JAVA6_HOME:-$EDEV_JDKS_HOME/jdk6}"